'''
This file defines the default configuration for the AcaFeed application.
It includes settings for the database, logging, and other application parameters.
'''

from dataclasses import dataclass

@dataclass
class FeedConfig:

    # Feedmanager configuration

    # Feedemmiter configuration
    feed_title: str = "Acafeed Generated Feed"
    repo: str = ""
    description: str = "This feed is generated by Acafeed."
    language: str = "en"

    # Feedclassifier configuration
    checkpoint_path: str = "model/model1_best.pt"
    tokenizer_name: str = "allenai/scibert_scivocab_uncased"
    max_title_length: int = 64
    threshold: float = 0.4
    device: str | None = None

    def to_dict(self):
        """Convert the configuration to a dictionary."""
        return {
            "feed_title": self.feed_title,
            "repo": self.repo,
            "description": self.description,
            "language": self.language,
            "checkpoint_path": self.checkpoint_path,
            "tokenizer_name": self.tokenizer_name,
            "max_title_length": self.max_title_length,
            "threshold": self.threshold,
            "device": self.device
        }
